language: node_js # 设置语言
node_js: stable # 设置相应版本
install:
    - npm install # 安装hexo及插件
script:
    - hexo clean # 清除
    - hexo g # 生成
after_script:
    - cd ./public
    - git init
    - git config user.name "WEIFENG2333" # 修改name
    - git config user.email "2715673327@qq.com" # 修改email
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages # GH_TOKEN 是在Travis中配置token的名称
branches:
    only:
        - master #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
    global:
        - GH_REF: github.com/WEIFENG2333/WEIFENG2333.github.io.git #设置GH_REF，注意更改yourname