sudo: false
language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - development # build development branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: development
  local-dir: public